### ISSUE TITLE
Aggiungere timeline per obiettivi progetto

### ISSUE THREAD

**Issue by DanielePucci** [fabio-pucci/hello-world#3]
Caro @fabio-pucci, mi sembra che nel [README](https://github.com/fabio-pucci/hello-world/blob/master/README.md) di questo repository non sia definita la timeline del progetto. Infatti, la timeline non è stata aggiunta **neanche** nelle ultime due PR #1  #2 

 Sarebbe possibile aggiungerla?

**Comment by fabio-pucci** [comment]
Caro @DanielePucci, l'ho aggiunta come collaboratore con diritti di scrittura su questo progetto! 😄 

Può procedere ad inserire la timeline che più ritiene opportuna **attraverso apertura pull request**

**Comment by DanielePucci** [comment]
Grazie @fabio-pucci, anche se speravo che il proprietario del repository avesse le idee chiare sulla timeline 🥇  Comunque procederò come suggerisci
